In [1]:
#problem 2e
import numpy as np

P = np.array([
    [9/10, 1/10, 0],
    [0,    7/8,  1/8],
    [2/5,  0,    3/5]
], dtype=float)

P50 = np.linalg.matrix_power(P, 50)
print(P50)

[[0.48780487 0.3902439  0.12195122]
 [0.4878049  0.3902439  0.12195121]
 [0.48780484 0.39024392 0.12195124]]


In [2]:
#problem 2f
n_steps = 10_000
states = np.zeros(n_steps + 1, dtype=int)  #include initial state
states[0] = 0  #start in G

rng = np.random.default_rng(777)

for t in range(n_steps):
    current = states[t]
    states[t+1] = rng.choice([0, 1, 2], p=P[current])

#fraction of time in G (including the starting time)
frac_G = np.mean(states == 0)

theory = 20/41

print("Simulated fraction in G:", frac_G)
print("Theoretical (from d):   ", theory)
print("Difference:", frac_G - theory)

Simulated fraction in G: 0.48195180481951805
Theoretical (from d):    0.4878048780487805
Difference: -0.005853073229262429
