In [1]:
#problem 3b
import numpy as np
import matplotlib.pyplot as plt

a = 0.99

#transition matrix 
P = np.array([
    [1-a, a,   0],
    [a,   0, 1-a],
    [0, 1-a,  a]
])

#transpose
A = P.T

#compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A = P^T:")
print(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrix A = P^T:
[[0.01 0.99 0.  ]
 [0.99 0.   0.01]
 [0.   0.01 0.99]]

Eigenvalues:
[-0.98503807  1.          0.98503807]

Eigenvectors:
[[ 0.70530531  0.57735027 -0.41135275]
 [-0.70889458  0.57735027 -0.40513595]
 [ 0.00358927  0.57735027  0.81648869]]
